<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('paises')->insert(['code'=>'AFG', 'nombre'=>'Afganistán']);
        \DB::table('paises')->insert(['code'=>'ALA', 'nombre'=>'Islas Åland']);
        \DB::table('paises')->insert(['code'=>'ALB', 'nombre'=>'Albania']);
        \DB::table('paises')->insert(['code'=>'DEU', 'nombre'=>'Alemania']);
        \DB::table('paises')->insert(['code'=>'AND', 'nombre'=>'Andorra']);
        \DB::table('paises')->insert(['code'=>'AGO', 'nombre'=>'Angola']);
        \DB::table('paises')->insert(['code'=>'AIA', 'nombre'=>'Anguila']);
        \DB::table('paises')->insert(['code'=>'ATA', 'nombre'=>'Antártida']);
        \DB::table('paises')->insert(['code'=>'ATG', 'nombre'=>'Antigua y Barbuda']);
        \DB::table('paises')->insert(['code'=>'SAU', 'nombre'=>'Arabia Saudita']);
        \DB::table('paises')->insert(['code'=>'DZA', 'nombre'=>'Argelia']);
        \DB::table('paises')->insert(['code'=>'ARG', 'nombre'=>'Argentina']);
        \DB::table('paises')->insert(['code'=>'ARM', 'nombre'=>'Armenia']);
        \DB::table('paises')->insert(['code'=>'ABW', 'nombre'=>'Aruba']);
        \DB::table('paises')->insert(['code'=>'AUS', 'nombre'=>'Australia']);
        \DB::table('paises')->insert(['code'=>'AUT', 'nombre'=>'Austria']);
        \DB::table('paises')->insert(['code'=>'AZE', 'nombre'=>'Azerbaiyán']);
        \DB::table('paises')->insert(['code'=>'BHS', 'nombre'=>'Bahamas (las)']);
        \DB::table('paises')->insert(['code'=>'BGD', 'nombre'=>'Bangladés']);
        \DB::table('paises')->insert(['code'=>'BRB', 'nombre'=>'Barbados']);
        \DB::table('paises')->insert(['code'=>'BHR', 'nombre'=>'Baréin']);
        \DB::table('paises')->insert(['code'=>'BEL', 'nombre'=>'Bélgica']);
        \DB::table('paises')->insert(['code'=>'BLZ', 'nombre'=>'Belice']);
        \DB::table('paises')->insert(['code'=>'BEN', 'nombre'=>'Benín']);
        \DB::table('paises')->insert(['code'=>'BMU', 'nombre'=>'Bermudas']);
        \DB::table('paises')->insert(['code'=>'BLR', 'nombre'=>'Bielorrusia']);
        \DB::table('paises')->insert(['code'=>'MMR', 'nombre'=>'Myanmar']);
        \DB::table('paises')->insert(['code'=>'BOL', 'nombre'=>'Bolivia, Estado Plurinacional de']);
        \DB::table('paises')->insert(['code'=>'BIH', 'nombre'=>'Bosnia y Herzegovina']);
        \DB::table('paises')->insert(['code'=>'BWA', 'nombre'=>'Botsuana']);
        \DB::table('paises')->insert(['code'=>'BRA', 'nombre'=>'Brasil']);
        \DB::table('paises')->insert(['code'=>'BRN', 'nombre'=>'Brunéi Darussalam']);
        \DB::table('paises')->insert(['code'=>'BGR', 'nombre'=>'Bulgaria']);
        \DB::table('paises')->insert(['code'=>'BFA', 'nombre'=>'Burkina Faso']);
        \DB::table('paises')->insert(['code'=>'BDI', 'nombre'=>'Burundi']);
        \DB::table('paises')->insert(['code'=>'BTN', 'nombre'=>'Bután']);
        \DB::table('paises')->insert(['code'=>'CPV', 'nombre'=>'Cabo Verde']);
        \DB::table('paises')->insert(['code'=>'KHM', 'nombre'=>'Camboya']);
        \DB::table('paises')->insert(['code'=>'CMR', 'nombre'=>'Camerún']);
        \DB::table('paises')->insert(['code'=>'CAN', 'nombre'=>'Canadá']);
        \DB::table('paises')->insert(['code'=>'QAT', 'nombre'=>'Catar']);
        \DB::table('paises')->insert(['code'=>'BES', 'nombre'=>'Bonaire, San Eustaquio y Saba']);
        \DB::table('paises')->insert(['code'=>'TCD', 'nombre'=>'Chad']);
        \DB::table('paises')->insert(['code'=>'CHL', 'nombre'=>'Chile']);
        \DB::table('paises')->insert(['code'=>'CHN', 'nombre'=>'China']);
        \DB::table('paises')->insert(['code'=>'CYP', 'nombre'=>'Chipre']);
        \DB::table('paises')->insert(['code'=>'COL', 'nombre'=>'Colombia']);
        \DB::table('paises')->insert(['code'=>'COM', 'nombre'=>'Comoras']);
        \DB::table('paises')->insert(['code'=>'PRK', 'nombre'=>'Corea (la República Democrática Popular de)']);
        \DB::table('paises')->insert(['code'=>'KOR', 'nombre'=>'Corea (la República de)']);
        \DB::table('paises')->insert(['code'=>'CIV', 'nombre'=>"Côte d'Ivoire"]);
        \DB::table('paises')->insert(['code'=>'CRI', 'nombre'=>'Costa Rica']);
        \DB::table('paises')->insert(['code'=>'HRV', 'nombre'=>'Croacia']);
        \DB::table('paises')->insert(['code'=>'CUB', 'nombre'=>'Cuba']);
        \DB::table('paises')->insert(['code'=>'CUW', 'nombre'=>'Curaçao']);
        \DB::table('paises')->insert(['code'=>'DNK', 'nombre'=>'Dinamarca']);
        \DB::table('paises')->insert(['code'=>'DMA', 'nombre'=>'Dominica']);
        \DB::table('paises')->insert(['code'=>'ECU', 'nombre'=>'Ecuador']);
        \DB::table('paises')->insert(['code'=>'EGY', 'nombre'=>'Egipto']);
        \DB::table('paises')->insert(['code'=>'SLV', 'nombre'=>'El Salvador']);
        \DB::table('paises')->insert(['code'=>'ARE', 'nombre'=>'Emiratos Árabes Unidos (Los)']);
        \DB::table('paises')->insert(['code'=>'ERI', 'nombre'=>'Eritrea']);
        \DB::table('paises')->insert(['code'=>'SVK', 'nombre'=>'Eslovaquia']);
        \DB::table('paises')->insert(['code'=>'SVN', 'nombre'=>'Eslovenia']);
        \DB::table('paises')->insert(['code'=>'ESP', 'nombre'=>'España']);
        \DB::table('paises')->insert(['code'=>'USA', 'nombre'=>'Estados Unidos (los)']);
        \DB::table('paises')->insert(['code'=>'EST', 'nombre'=>'Estonia']);
        \DB::table('paises')->insert(['code'=>'ETH', 'nombre'=>'Etiopía']);
        \DB::table('paises')->insert(['code'=>'PHL', 'nombre'=>'Filipinas (las)']);
        \DB::table('paises')->insert(['code'=>'FIN', 'nombre'=>'Finlandia']);
        \DB::table('paises')->insert(['code'=>'FJI', 'nombre'=>'Fiyi']);
        \DB::table('paises')->insert(['code'=>'FRA', 'nombre'=>'Francia']);
        \DB::table('paises')->insert(['code'=>'GAB', 'nombre'=>'Gabón']);
        \DB::table('paises')->insert(['code'=>'GMB', 'nombre'=>'Gambia (La)']);
        \DB::table('paises')->insert(['code'=>'GEO', 'nombre'=>'Georgia']);
        \DB::table('paises')->insert(['code'=>'GHA', 'nombre'=>'Ghana']);
        \DB::table('paises')->insert(['code'=>'GIB', 'nombre'=>'Gibraltar']);
        \DB::table('paises')->insert(['code'=>'GRD', 'nombre'=>'Granada']);
        \DB::table('paises')->insert(['code'=>'GRC', 'nombre'=>'Grecia']);
        \DB::table('paises')->insert(['code'=>'GRL', 'nombre'=>'Groenlandia']);
        \DB::table('paises')->insert(['code'=>'GLP', 'nombre'=>'Guadalupe']);
        \DB::table('paises')->insert(['code'=>'GUM', 'nombre'=>'Guam']);
        \DB::table('paises')->insert(['code'=>'GTM', 'nombre'=>'Guatemala']);
        \DB::table('paises')->insert(['code'=>'GUF', 'nombre'=>'Guayana Francesa']);
        \DB::table('paises')->insert(['code'=>'GGY', 'nombre'=>'Guernsey']);
        \DB::table('paises')->insert(['code'=>'GIN', 'nombre'=>'Guinea']);
        \DB::table('paises')->insert(['code'=>'GNB', 'nombre'=>'Guinea-Bisáu']);
        \DB::table('paises')->insert(['code'=>'GNQ', 'nombre'=>'Guinea Ecuatorial']);
        \DB::table('paises')->insert(['code'=>'GUY', 'nombre'=>'Guyana']);
        \DB::table('paises')->insert(['code'=>'HTI', 'nombre'=>'Haití']);
        \DB::table('paises')->insert(['code'=>'HND', 'nombre'=>'Honduras']);
        \DB::table('paises')->insert(['code'=>'HKG', 'nombre'=>'Hong Kong']);
        \DB::table('paises')->insert(['code'=>'HUN', 'nombre'=>'Hungría']);
        \DB::table('paises')->insert(['code'=>'IND', 'nombre'=>'India']);
        \DB::table('paises')->insert(['code'=>'IDN', 'nombre'=>'Indonesia']);
        \DB::table('paises')->insert(['code'=>'IRQ', 'nombre'=>'Irak']);
        \DB::table('paises')->insert(['code'=>'IRN', 'nombre'=>'Irán (la República Islámica de)']);
        \DB::table('paises')->insert(['code'=>'IRL', 'nombre'=>'Irlanda']);
        \DB::table('paises')->insert(['code'=>'BVT', 'nombre'=>'Isla Bouvet']);
        \DB::table('paises')->insert(['code'=>'IMN', 'nombre'=>'Isla de Man']);
        \DB::table('paises')->insert(['code'=>'CXR', 'nombre'=>'Isla de Navidad']);
        \DB::table('paises')->insert(['code'=>'NFK', 'nombre'=>'Isla Norfolk']);
        \DB::table('paises')->insert(['code'=>'ISL', 'nombre'=>'Islandia']);
        \DB::table('paises')->insert(['code'=>'CYM', 'nombre'=>'Islas Caimán (las)']);
        \DB::table('paises')->insert(['code'=>'CCK', 'nombre'=>'Islas Cocos (Keeling)']);
        \DB::table('paises')->insert(['code'=>'COK', 'nombre'=>'Islas Cook (las)']);
        \DB::table('paises')->insert(['code'=>'FRO', 'nombre'=>'Islas Feroe (las)']);
        \DB::table('paises')->insert(['code'=>'SGS', 'nombre'=>'Georgia del sur y las islas sandwich del sur']);
        \DB::table('paises')->insert(['code'=>'HMD', 'nombre'=>'Isla Heard e Islas McDonald']);
        \DB::table('paises')->insert(['code'=>'FLK', 'nombre'=>'Islas Malvinas [Falkland] (las)']);
        \DB::table('paises')->insert(['code'=>'MNP', 'nombre'=>'Islas Marianas del Norte (las)']);
        \DB::table('paises')->insert(['code'=>'MHL', 'nombre'=>'Islas Marshall (las)']);
        \DB::table('paises')->insert(['code'=>'PCN', 'nombre'=>'Pitcairn']);
        \DB::table('paises')->insert(['code'=>'SLB', 'nombre'=>'Islas Salomón (las)']);
        \DB::table('paises')->insert(['code'=>'TCA', 'nombre'=>'Islas Turcas y Caicos (las)']);
        \DB::table('paises')->insert(['code'=>'UMI', 'nombre'=>'Islas de Ultramar Menores de Estados Unidos (las)']);
        \DB::table('paises')->insert(['code'=>'VGB', 'nombre'=>'Islas Vírgenes (Británicas)']);
        \DB::table('paises')->insert(['code'=>'VIR', 'nombre'=>'Islas Vírgenes (EE.UU.)']);
        \DB::table('paises')->insert(['code'=>'ISR', 'nombre'=>'Israel']);
        \DB::table('paises')->insert(['code'=>'ITA', 'nombre'=>'Italia']);
        \DB::table('paises')->insert(['code'=>'JAM', 'nombre'=>'Jamaica']);
        \DB::table('paises')->insert(['code'=>'JPN', 'nombre'=>'Japón']);
        \DB::table('paises')->insert(['code'=>'JEY', 'nombre'=>'Jersey']);
        \DB::table('paises')->insert(['code'=>'JOR', 'nombre'=>'Jordania']);
        \DB::table('paises')->insert(['code'=>'KAZ', 'nombre'=>'Kazajistán']);
        \DB::table('paises')->insert(['code'=>'KEN', 'nombre'=>'Kenia']);
        \DB::table('paises')->insert(['code'=>'KGZ', 'nombre'=>'Kirguistán']);
        \DB::table('paises')->insert(['code'=>'KIR', 'nombre'=>'Kiribati']);
        \DB::table('paises')->insert(['code'=>'KWT', 'nombre'=>'Kuwait']);
        \DB::table('paises')->insert(['code'=>'LAO', 'nombre'=>'Lao, (la) República Democrática Popular']);
        \DB::table('paises')->insert(['code'=>'LSO', 'nombre'=>'Lesoto']);
        \DB::table('paises')->insert(['code'=>'LVA', 'nombre'=>'Letonia']);
        \DB::table('paises')->insert(['code'=>'LBN', 'nombre'=>'Líbano']);
        \DB::table('paises')->insert(['code'=>'LBR', 'nombre'=>'Liberia']);
        \DB::table('paises')->insert(['code'=>'LBY', 'nombre'=>'Libia']);
        \DB::table('paises')->insert(['code'=>'LIE', 'nombre'=>'Liechtenstein']);
        \DB::table('paises')->insert(['code'=>'LTU', 'nombre'=>'Lituania']);
        \DB::table('paises')->insert(['code'=>'LUX', 'nombre'=>'Luxemburgo']);
        \DB::table('paises')->insert(['code'=>'MAC', 'nombre'=>'Macao']);
        \DB::table('paises')->insert(['code'=>'MDG', 'nombre'=>'Madagascar']);
        \DB::table('paises')->insert(['code'=>'MYS', 'nombre'=>'Malasia']);
        \DB::table('paises')->insert(['code'=>'MWI', 'nombre'=>'Malaui']);
        \DB::table('paises')->insert(['code'=>'MDV', 'nombre'=>'Maldivas']);
        \DB::table('paises')->insert(['code'=>'MLI', 'nombre'=>'Malí']);
        \DB::table('paises')->insert(['code'=>'MLT', 'nombre'=>'Malta']);
        \DB::table('paises')->insert(['code'=>'MAR', 'nombre'=>'Marruecos']);
        \DB::table('paises')->insert(['code'=>'MTQ', 'nombre'=>'Martinica']);
        \DB::table('paises')->insert(['code'=>'MUS', 'nombre'=>'Mauricio']);
        \DB::table('paises')->insert(['code'=>'MRT', 'nombre'=>'Mauritania']);
        \DB::table('paises')->insert(['code'=>'MYT', 'nombre'=>'Mayotte']);
        \DB::table('paises')->insert(['code'=>'MEX', 'nombre'=>'México']);
        \DB::table('paises')->insert(['code'=>'FSM', 'nombre'=>'Micronesia (los Estados Federados de)']);
        \DB::table('paises')->insert(['code'=>'MDA', 'nombre'=>'Moldavia (la República de)']);
        \DB::table('paises')->insert(['code'=>'MCO', 'nombre'=>'Mónaco']);
        \DB::table('paises')->insert(['code'=>'MNG', 'nombre'=>'Mongolia']);
        \DB::table('paises')->insert(['code'=>'MNE', 'nombre'=>'Montenegro']);
        \DB::table('paises')->insert(['code'=>'MSR', 'nombre'=>'Montserrat']);
        \DB::table('paises')->insert(['code'=>'MOZ', 'nombre'=>'Mozambique']);
        \DB::table('paises')->insert(['code'=>'NAM', 'nombre'=>'Namibia']);
        \DB::table('paises')->insert(['code'=>'NRU', 'nombre'=>'Nauru']);
        \DB::table('paises')->insert(['code'=>'NPL', 'nombre'=>'Nepal']);
        \DB::table('paises')->insert(['code'=>'NIC', 'nombre'=>'Nicaragua']);
        \DB::table('paises')->insert(['code'=>'NER', 'nombre'=>'Níger (el)']);
        \DB::table('paises')->insert(['code'=>'NGA', 'nombre'=>'Nigeria']);
        \DB::table('paises')->insert(['code'=>'NIU', 'nombre'=>'Niue']);
        \DB::table('paises')->insert(['code'=>'NOR', 'nombre'=>'Noruega']);
        \DB::table('paises')->insert(['code'=>'NCL', 'nombre'=>'Nueva Caledonia']);
        \DB::table('paises')->insert(['code'=>'NZL', 'nombre'=>'Nueva Zelanda']);
        \DB::table('paises')->insert(['code'=>'OMN', 'nombre'=>'Omán']);
        \DB::table('paises')->insert(['code'=>'NLD', 'nombre'=>'Países Bajos (los)']);
        \DB::table('paises')->insert(['code'=>'PAK', 'nombre'=>'Pakistán']);
        \DB::table('paises')->insert(['code'=>'PLW', 'nombre'=>'Palaos']);
        \DB::table('paises')->insert(['code'=>'PSE', 'nombre'=>'Palestina, Estado de']);
        \DB::table('paises')->insert(['code'=>'PAN', 'nombre'=>'Panamá']);
        \DB::table('paises')->insert(['code'=>'PNG', 'nombre'=>'Papúa Nueva Guinea']);
        \DB::table('paises')->insert(['code'=>'PRY', 'nombre'=>'Paraguay']);
        \DB::table('paises')->insert(['code'=>'PER', 'nombre'=>'Perú']);
        \DB::table('paises')->insert(['code'=>'PYF', 'nombre'=>'Polinesia Francesa']);
        \DB::table('paises')->insert(['code'=>'POL', 'nombre'=>'Polonia']);
        \DB::table('paises')->insert(['code'=>'PRT', 'nombre'=>'Portugal']);
        \DB::table('paises')->insert(['code'=>'PRI', 'nombre'=>'Puerto Rico']);
        \DB::table('paises')->insert(['code'=>'GBR', 'nombre'=>'Reino Unido (el)']);
        \DB::table('paises')->insert(['code'=>'CAF', 'nombre'=>'República Centroafricana (la)']);
        \DB::table('paises')->insert(['code'=>'CZE', 'nombre'=>'República Checa (la)']);
        \DB::table('paises')->insert(['code'=>'MKD', 'nombre'=>'Macedonia (la antigua República Yugoslava de)']);
        \DB::table('paises')->insert(['code'=>'COG', 'nombre'=>'Congo']);
        \DB::table('paises')->insert(['code'=>'COD', 'nombre'=>'Congo (la República Democrática del)']);
        \DB::table('paises')->insert(['code'=>'DOM', 'nombre'=>'República Dominicana (la)']);
        \DB::table('paises')->insert(['code'=>'REU', 'nombre'=>'Reunión']);
        \DB::table('paises')->insert(['code'=>'RWA', 'nombre'=>'Ruanda']);
        \DB::table('paises')->insert(['code'=>'ROU', 'nombre'=>'Rumania']);
        \DB::table('paises')->insert(['code'=>'RUS', 'nombre'=>'Rusia, (la) Federación de']);
        \DB::table('paises')->insert(['code'=>'ESH', 'nombre'=>'Sahara Occidental']);
        \DB::table('paises')->insert(['code'=>'WSM', 'nombre'=>'Samoa']);
        \DB::table('paises')->insert(['code'=>'ASM', 'nombre'=>'Samoa Americana']);
        \DB::table('paises')->insert(['code'=>'BLM', 'nombre'=>'San Bartolomé']);
        \DB::table('paises')->insert(['code'=>'KNA', 'nombre'=>'San Cristóbal y Nieves']);
        \DB::table('paises')->insert(['code'=>'SMR', 'nombre'=>'San Marino']);
        \DB::table('paises')->insert(['code'=>'MAF', 'nombre'=>'San Martín (parte francesa)']);
        \DB::table('paises')->insert(['code'=>'SPM', 'nombre'=>'San Pedro y Miquelón']);
        \DB::table('paises')->insert(['code'=>'VCT', 'nombre'=>'San Vicente y las Granadinas']);
        \DB::table('paises')->insert(['code'=>'SHN', 'nombre'=>'Santa Helena, Ascensión y Tristán de Acuña']);
        \DB::table('paises')->insert(['code'=>'LCA', 'nombre'=>'Santa Lucía']);
        \DB::table('paises')->insert(['code'=>'STP', 'nombre'=>'Santo Tomé y Príncipe']);
        \DB::table('paises')->insert(['code'=>'SEN', 'nombre'=>'Senegal']);
        \DB::table('paises')->insert(['code'=>'SRB', 'nombre'=>'Serbia']);
        \DB::table('paises')->insert(['code'=>'SYC', 'nombre'=>'Seychelles']);
        \DB::table('paises')->insert(['code'=>'SLE', 'nombre'=>'Sierra leona']);
        \DB::table('paises')->insert(['code'=>'SGP', 'nombre'=>'Singapur']);
        \DB::table('paises')->insert(['code'=>'SXM', 'nombre'=>'Sint Maarten (parte holandesa)']);
        \DB::table('paises')->insert(['code'=>'SYR', 'nombre'=>'Siria, (la) República Árabe']);
        \DB::table('paises')->insert(['code'=>'SOM', 'nombre'=>'Somalia']);
        \DB::table('paises')->insert(['code'=>'LKA', 'nombre'=>'Sri Lanka']);
        \DB::table('paises')->insert(['code'=>'SWZ', 'nombre'=>'Suazilandia']);
        \DB::table('paises')->insert(['code'=>'ZAF', 'nombre'=>'Sudáfrica']);
        \DB::table('paises')->insert(['code'=>'SDN', 'nombre'=>'Sudán (el)']);
        \DB::table('paises')->insert(['code'=>'SSD', 'nombre'=>'Sudán del Sur']);
        \DB::table('paises')->insert(['code'=>'SWE', 'nombre'=>'Suecia']);
        \DB::table('paises')->insert(['code'=>'CHE', 'nombre'=>'Suiza']);
        \DB::table('paises')->insert(['code'=>'SUR', 'nombre'=>'Surinam']);
        \DB::table('paises')->insert(['code'=>'SJM', 'nombre'=>'Svalbard y Jan Mayen']);
        \DB::table('paises')->insert(['code'=>'THA', 'nombre'=>'Tailandia']);
        \DB::table('paises')->insert(['code'=>'TWN', 'nombre'=>'Taiwán (Provincia de China)']);
        \DB::table('paises')->insert(['code'=>'TZA', 'nombre'=>'Tanzania, República Unida de']);
        \DB::table('paises')->insert(['code'=>'TJK', 'nombre'=>'Tayikistán']);
        \DB::table('paises')->insert(['code'=>'IOT', 'nombre'=>'Territorio Británico del Océano Índico (el)']);
        \DB::table('paises')->insert(['code'=>'ATF', 'nombre'=>'Territorios Australes Franceses (los)']);
        \DB::table('paises')->insert(['code'=>'TLS', 'nombre'=>'Timor-Leste']);
        \DB::table('paises')->insert(['code'=>'TGO', 'nombre'=>'Togo']);
        \DB::table('paises')->insert(['code'=>'TKL', 'nombre'=>'Tokelau']);
        \DB::table('paises')->insert(['code'=>'TON', 'nombre'=>'Tonga']);
        \DB::table('paises')->insert(['code'=>'TTO', 'nombre'=>'Trinidad y Tobago']);
        \DB::table('paises')->insert(['code'=>'TUN', 'nombre'=>'Túnez']);
        \DB::table('paises')->insert(['code'=>'TKM', 'nombre'=>'Turkmenistán']);
        \DB::table('paises')->insert(['code'=>'TUR', 'nombre'=>'Turquía']);
        \DB::table('paises')->insert(['code'=>'TUV', 'nombre'=>'Tuvalu']);
        \DB::table('paises')->insert(['code'=>'UKR', 'nombre'=>'Ucrania']);
        \DB::table('paises')->insert(['code'=>'UGA', 'nombre'=>'Uganda']);
        \DB::table('paises')->insert(['code'=>'URY', 'nombre'=>'Uruguay']);
        \DB::table('paises')->insert(['code'=>'UZB', 'nombre'=>'Uzbekistán']);
        \DB::table('paises')->insert(['code'=>'VUT', 'nombre'=>'Vanuatu']);
        \DB::table('paises')->insert(['code'=>'VAT', 'nombre'=>'Santa Sede[Estado de la Ciudad del Vaticano] (la)']);
        \DB::table('paises')->insert(['code'=>'VEN', 'nombre'=>'Venezuela, República Bolivariana de']);
        \DB::table('paises')->insert(['code'=>'VNM', 'nombre'=>'Viet Nam']);
        \DB::table('paises')->insert(['code'=>'WLF', 'nombre'=>'Wallis y Futuna']);
        \DB::table('paises')->insert(['code'=>'YEM', 'nombre'=>'Yemen']);
        \DB::table('paises')->insert(['code'=>'DJI', 'nombre'=>'Yibuti']);
        \DB::table('paises')->insert(['code'=>'ZMB', 'nombre'=>'Zambia']);
        \DB::table('paises')->insert(['code'=>'ZWE', 'nombre'=>'Zimbabue']);
        \DB::table('paises')->insert(['code'=>'ZZZ', 'nombre'=>'Países no declarados']);

    }
}
